# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

$year = '2026'
$lecture = 'comp_a'
$local_dir = File.join('~/Sites/new_ist/Lectures',$year)
$lec_dir = File.expand_path(File.join($local_dir,$lecture))

task :default do
  p ['$lec_dir', $lec_dir]
  system "rake -T"
end

desc "remove image dir in local site"
task :rm_image_dir => :show_dirs do 
  p comm = "rm -rf #{File.join($lec_dir, $source_dir)}"
  system comm
  exit
end

desc "show necessary dirs for display light table DIR public." #desc -> description
task :show_dirs do # any name on task_name
  if ARGV[1] == nil
    puts "\nNeed source dir name.\n".red
    exit
  else
    $source_dir = ARGV[1]
    $source_yaml = $source_dir + ".yaml"
    $source_html = $source_dir + ".html"
  end
  puts "Setup following dirs:".blue
  puts "#{$lec_dir}".blue
  puts "#{$ist_dir}".blue
  puts ""
end

desc "make DIR light table" #desc -> description
task :mk_light_table => :show_dirs do # any name on task_name
  $source_yaml = $source_dir + ".yaml"
  p comm = "hc mk_light_table -d #{$source_dir}"
  system comm
  puts "\nFor making light table structured, modify #{$source_yaml}.".green
  puts "hc mk_light_table -g #{$souce_yaml}".green
  exit
end

desc "commit local dir" #desc -> description
task :commit => :show_dirs do # any name on task_name
  ["mkdir #{File.join($lec_dir, $source_dir)}",
   "cp -rf #{$source_dir} #{$lec_dir}",
   "cp style.css #{$lec_dir}",
   "cp #{$source_html} #{$lec_dir}",
   "chmod -R a+r #{$lec_dir}"
   ].each do |comm|
    p comm
    system comm
  end
  exit
end

desc "push light tables to web server"
task :push => :show_dirs do
  $ist_dir = File.join("nishitani@ist.ksc.kwansei.ac.jp:~/public_html/Lectures",
                       $year)
  $https_dir = File.join("https://ist.ksc.kwansei.ac.jp/~nishitani/Lectures",
                         $year, $lecture, $source_html)
  ["rsync --exclude .git -auvz -e ssh ~/Sites/new_ist/ nishitani@ist.ksc.kwansei.ac.jp:~/public_html",
   "open #{$https_dir}"].each do |comm|
    puts comm
    system comm
  end
end
