# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

$year = '2026'
$lecture = 'comp_a'
$local_dir = File.join('~/Sites/new_ist/Lectures',$year)
$lec_dir = File.expand_path(File.join($local_dir,$lecture))
$source_dir = 'readme_26s'
$source_html = 'readme_26s.html'
task :default do
  system "rake -T"
end

desc "make DIR light table" #desc -> description
task :mk_light_table => :show_dirs do # any name on task_name
  $source_yaml = $source_dir + ".yaml"
  puts "\nFor making light table structured, modify #{$source_yaml}.".green
  puts "hc mk_light_table -g #{$source_yaml}".green
  exit
end

desc "commit local dir" #desc -> description
task :commit do # any name on task_name
  [#"mkdir #{File.join($lec_dir, $source_dir)}",
   "cp -rf #{$source_dir} #{$lec_dir}",
   "cp style.css #{$lec_dir}",
   "cp #{$source_html} #{$lec_dir}",
   "chmod -R a+r #{$lec_dir}"
   ].each do |comm|
    p comm
    system comm
  end
  exit
end

desc "push light tables to web server"
task :push do
  $ist_dir = File.join("nishitani@ist.ksc.kwansei.ac.jp:~/public_html/Lectures",
                       $year)
  $https_dir = File.join("https://ist.ksc.kwansei.ac.jp/~nishitani/Lectures",
                         $year, $lecture, $source_html)
  ["rsync --exclude .git -auvz -e ssh ~/Sites/new_ist/ nishitani@ist.ksc.kwansei.ac.jp:~/public_html",
   "open #{$https_dir}"].each do |comm|
    
    puts comm
    system comm
  end
end
